version: '3.8'
services:
  postgres:
    image: postgres:13.5
    environment:
      - POSTGRES_DB=high-volume-concert-booking
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  test-postgres:
    image: postgres:13.5
    environment:
      - POSTGRES_DB=high-volume-concert-booking-test
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    volumes:
      - test-postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  postgres:
  test-postgres:
